title: Smart Nation Singapore
url: https://www.smartnation.gov.sg/
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#ed1a3b"
  secondary-color: "#1a5ded"
  media-colors:
    - title: media-color-one
      color: "#678a00"
    - title: media-color-two
      color: "#FF6633"
    - title: media-color-three
      color: "#00B5E2"
    - title: media-color-four
      color: "#CC3366"
    - title: media-color-five
      color: "#0180a0"
resources_name: media-hub
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: test test
staging: https://smartnationsg-staging.netlify.app
prod: https://smartnationsg-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
is_government: true
